name: Renovate

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Configure renovate
        env:
          RENOVATE_CONFIG_FILE: renovate.json
        uses: renovatebot/github-action@v46.1.8
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
